export const FETCH_START = 'menu/FETCH_START';
export const FETCH_ERROR = 'menu/FETCH_ERROR';
export const FETCH_SUCCESS_ALL_ITEMS = 'menu/FETCH_SUCCESS_ALL_ITEMS';
export const FETCH_SUCCESS_ALL_CATEGORIES = 'menu/FETCH_SUCCESS_ALL_CATEGORIES';

export const CHANGE_FILTER = 'menu/CHANGE_FILTER';
